language: java
notifications:
  email: false
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: ubl-analytics
    token:
      secure: $SONAR_TOKEN
before_install:
  - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
  - unzip sonar-scanner-cli-3.3.0.1492-linux.zip -d $HOME/travis.sonarscanner
  - export SONAR_SCANNER_HOME=${TRAVIS_HOME}/.sonarscanner/sonar-scanner-3.3.0.1492-linux
install:
  - cp ./configuration/settings.xml $HOME/.m2/settings.xml
  - mvn install -P !docker -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jobs:
  include:
    - stage: Test
      script:
        - mvn test -Pcoverage
        - sonar-scanner
