language: java
notifications:
  email: false
jdk:
  - openjdk8
addons:
  sonarcloud:https://codecov.io/gh/ubl-analytics/analytics/pulls
    organization: ubl-analytics
    token:
      secure: $SONAR_TOKEN
install:
  - mvn install -P !docker -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jobs:
  include:
    - stage: Test
      script:
        - mvn test
        - mvn sonar:sonar -Pcoverage
