language: java
notifications:
  email: false
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: ubl-analytics
    token:
      secure: $SONAR_TOKEN
install:
  - mvn install -P !docker -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jobs:
  include:
    - stage: Test
      script:
        - mvn test -Pcoverage
        - bash <(curl -s https://codecov.io/bash)
        - mvn sonar:sonar -Pcoverage
#        - ./travis/sonarcloud.sh
